version: '2.1'

jobs:
  maven_test:
    docker:
      - image: cimg/openjdk:11.0.17
    steps:
      - run:
          name: "Install Node"
          command: |
            sudo apt-get install -y curl \
            && curl -sL https://deb.nodesource.com/setup_20.x | sudo bash - \
            && sudo apt-get install -y nodejs \
            && curl -L https://www.npmjs.com/install.sh | sudo sh
      - checkout
      - run:
          name: "run"
          command: "mvn deploy -s etc/build/settings.xml"