version: '2.1'

jobs:
  maven_test:
    docker:
      - image: cimg/openjdk:11.0.17
    steps:
      - run:
          name: "Set Environment Variables"
          command: |
            echo "export GITHUB_RELEASE_REPO_TOKEN=<your_github_token>" >> $BASH_ENV
            echo "export GITHUB_RELEASE_REPO_URL=<your_github_repo_url>" >> $BASH_ENV
      - run:
          name: "Install Node"
          command: |
            sudo apt-get install -y curl \
            && curl -sL https://deb.nodesource.com/setup_20.x | sudo bash - \
            && sudo apt-get install -y nodejs \
            && curl -L https://www.npmjs.com/install.sh | sudo sh
      - checkout
      - run:
          name: "Run unit tests"
          command: "mvn clean test -s etc/build/settings.xml"
  build:
    docker:
      - image: cimg/openjdk:11.0.17
    steps:
      - run:
          name: "Install Node"
          command: |
            sudo apt-get install -y curl \
            && curl -sL https://deb.nodesource.com/setup_20.x | sudo bash - \
            && sudo apt-get install -y nodejs \
            && curl -L https://www.npmjs.com/install.sh | sudo sh
      - checkout
      - run:
          name: "Artifact Build"
          command: |
            mvn clean deploy -s etc/build/settings.xml